import React, { useState, useEffect } from "react";
import Head from "next/head";
import Header from "../../components/Header";
import {motion} from "framer-motion";
import {router} from "next/client";

const Payment = () => {

  const amount = 40.26;

  const options = {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'content-type': 'application/json',
      Authorization: 'd6aa2703655f4ba2af2a56202961ca86:dXbCgzYBMibj8ZwuQMd2NXr6rtvjZ8'
    },
    body: JSON.stringify({
      recipient: 'testing@checkbook.io',
      name: 'Widgets Inc.',
      amount: amount,
      description: 'Test Payment'
    })
  }

  const makePayment = () => {
    fetch('https://demo.checkbook.io/v3/check/digital', options)
      .then(response => response.json())
      .then(response => console.log(response))
      .catch(err => console.error(err));
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="h-screen w-full py-36 px-4 "
    >
      <Head>
        <title>SecondSwipe</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
        />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <img
          className="w-96"
          src="https://i.ibb.co/QPD8gS6/fulllogo.png"
          alt=""
        />
        <div className="bg-white shadow lg:w-1/3  md:w-1/2 w-full p-10 mt-16 text-center rounded-md">
          <p
            tabIndex={0}
            role="heading"
            className="text-2xl font-bold leading-6 text-gray-800"
          >
            The following amount will be charged after verification of purchase.
          </p>
          <div className="center-container">
            <div className="AIBox">
              ${amount}
            </div>
          </div>
          <p>
            Powered by
          </p>
          <div className="checkbook">
            <img src="https://s3-us-west-2.amazonaws.com/cbi-image-service-prd/modified/384dd0db-1e8f-4dc4-bc9a-771bdab42145.png" />
          </div>
          <div className="center-container">
          <button
            onClick={() => router.push('/')}
            type="button"
            className="upload-btn"
          >
            Confirm
          </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default Payment;
