import React, { useState, useEffect } from "react";
import Head from "next/head";
import Header from "../../components/Header";

const Payment = () => {

  const sdk = require('api')('@checkbook-docs/v3.1#epdp15jldsybsok');

  useEffect(() => {
    sdk.auth('d6aa2703655f4ba2af2a56202961ca86:dXbCgzYBMibj8ZwuQMd2NXr6rtvjZ8');
    sdk.postCheckDigital({
      recipient: 'testing@checkbook.io',
      name: 'Widgets Inc.',
      amount: 5,
      description: 'Test Payment'
    })
      .then(({ data }) => console.log(data))
      .catch(err => console.error(err));
  })

  return (
    <>
      <Head>
        <title>SecondSwipe</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
        />
      </Head>
      <Header isShow={false} />
      <div className="App">
        <header className="App-header">
        </header>
      </div>
    </>
  );
};

export default Payment;
